name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag naspuka/docker-gitaction:latest
    
    - name: Push Docker Image
      run: docker login -u naspuka -p ${{ secrets.DOCKER_TOKEN }} && docker push naspuka/docker-gitaction:latest
